"""POST /process — dequeue one job, run vision analysis, persist if confidence ≥ threshold."""

from __future__ import annotations

import base64
import logging
import mimetypes
import smtplib
from datetime import datetime
from email.message import EmailMessage
from pathlib import Path

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel

from server.core.config import get_settings
from server.db.connection import get_transaction
from server.db.crud import insert_violation
from server.services.vision import VisionResult, analyze_image
from server.worker.queue import dequeue, queue_length

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/process", tags=["process"])


class VisionDetail(BaseModel):
    is_violation: bool
    confidence: float
    number_plate: str | None
    violation_type: str | None


class ProcessResponse(BaseModel):
    job_id: str
    action: str  # "saved" | "skipped" | "no_job"
    vision: VisionDetail | None
    violation_id: str | None  # UUID of the saved DB row, if any
    queue_remaining: int


def _read_image(job: dict) -> bytes:
    """Return raw image bytes from the job payload (event.evidence or legacy format)."""
    if event := job.get("event"):
        if evidence := event.get("evidence"):
            for ref in evidence:
                if ref.get("kind") == "motorcycle_crop":
                    uri = ref.get("uri")
                    if uri:
                        p = Path(uri)
                        if p.exists():
                            return p.read_bytes()
                        logger.warning("Evidence path does not exist: %s", p)
    if b64 := job.get("image_b64"):
        return base64.b64decode(b64)
    if path := job.get("image_path"):
        p = Path(path)
        if p.exists():
            return p.read_bytes()
        logger.warning("Image path does not exist: %s", p)
    logger.warning("Job has no usable image source: %s", job.get("job_id"))
    raise ValueError(f"Job {job.get('job_id')} has no usable image source.")


def _send_violation_email(
    image_bytes: bytes,
    image_path: str | None,
    job_id: str,
    violation_id: str,
    camera_id: str | None,
    captured_at: datetime,
    number_plate: str | None,
    violation_type: str | None,
    confidence: float,
) -> None:
    """
    Send a violation alert email to the configured RECEIVER_MAIL via Gmail SMTP.

    Uses SENDER_MAIL + SENDER_APP_PASSWORD from settings (Gmail App Password,
    not the account password). Attaches the evidence image.

    This is intentionally called outside the DB transaction so that an SMTP
    failure never rolls back an already-committed violation row.
    """
    settings = get_settings()

    subject = f"Traffic Violation Alert — Plate: {number_plate or 'Unknown'} | ID: {violation_id}"

    body = f"""\
Dear Officer,

A traffic violation has been detected and confirmed by the automated monitoring system.
Please find the details below and the evidence image attached.

─────────────────────────────────────
  VIOLATION DETAILS
─────────────────────────────────────
  Violation ID   : {violation_id}
  Job Reference  : {job_id}
  Number Plate   : {number_plate or "Not detected"}
  Violation Type : {violation_type or "Not specified"}
  Camera ID      : {camera_id or "Unknown"}
  Captured At    : {captured_at.strftime("%d %b %Y, %H:%M:%S")}
  Confidence     : {confidence * 100:.1f}%
─────────────────────────────────────

The attached image is the cropped evidence frame captured at the time of the violation.
Kindly take the necessary action as per the applicable traffic regulations.

This is an automated alert generated by the Traffic Violation Monitoring System.
Please do not reply to this email.

Regards,
Traffic Violation Monitoring System
"""

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = settings.SENDER_MAIL
    msg["To"] = settings.RECEIVER_MAIL
    msg.set_content(body)

    # Attach the evidence image
    # Derive a sensible filename — fall back to job_id.jpg if no path available
    if image_path:
        filename = Path(image_path).name
    else:
        filename = f"violation_{job_id}.jpg"

    mime_type, _ = mimetypes.guess_type(filename)
    if mime_type and "/" in mime_type:
        maintype, subtype = mime_type.split("/", 1)
    else:
        maintype, subtype = "image", "jpeg"

    msg.add_attachment(image_bytes, maintype=maintype, subtype=subtype, filename=filename)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(settings.MAIL_FROM, settings.SMTP_PASSWORD)
            smtp.send_message(msg)
        logger.info(
            "Violation alert email sent for violation %s (plate=%s) to %s",
            violation_id,
            number_plate,
            settings.MAIL_TO,
        )
    except smtplib.SMTPAuthenticationError:
        logger.error(
            "SMTP authentication failed — check SENDER_MAIL and SENDER_APP_PASSWORD in settings."
        )
    except smtplib.SMTPException as exc:
        logger.exception("Failed to send violation alert email for job %s: %s", job_id, exc)


@router.post(
    "",
    response_model=ProcessResponse,
    summary="Dequeue one job, run vision analysis, persist if violation confirmed",
)
async def process_next() -> ProcessResponse:
    """
    Pulls the next job from the violation queue and runs the full pipeline:

    1. **Dequeue** — BRPOP with a 5-second timeout; returns `no_job` if empty.
    2. **Vision analysis** — sends the image to the configured vision model.
    3. **Confidence gate** — only writes to the DB if
       confidence >= `CONFIDENCE_THRESHOLD` (default 0.9).
    4. **Persist** — inserts a row into `violations` with status `confirmed`.
    5. **Email alert** — sends a Gmail notification with the evidence image attached
       to `RECEIVER_MAIL`. Failures are logged but do not affect the HTTP response.
    6. **Skip** — if below threshold, logs and returns `skipped` (nothing written).

    Designed to be called by a worker loop or an external scheduler.
    """

    job = await dequeue(timeout=5)
    remaining = await queue_length()

    if job is None:
        return ProcessResponse(
            job_id="",
            action="no_job",
            vision=None,
            violation_id=None,
            queue_remaining=remaining,
        )

    job_id: str = job.get("job_id", "unknown")
    camera_id: str | None = job.get("camera_id")
    captured_at = datetime.fromisoformat(job["captured_at"])

    logger.info("Processing job %s (camera=%s)", job_id, camera_id)

    try:
        image_bytes = _read_image(job)
    except (ValueError, KeyError) as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=str(exc),
        ) from exc

    try:
        result: VisionResult = await analyze_image(image_bytes)
    except Exception as exc:
        logger.exception("Vision model failed for job %s", job_id)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Vision model error: {exc}",
        ) from exc

    vision_detail = VisionDetail(
        is_violation=result.is_violation,
        confidence=result.confidence,
        number_plate=result.number_plate,
        violation_type=result.violation_type,
    )

    logger.info(
        "Job %s — violation=%s confidence=%.3f plate=%s",
        job_id,
        result.is_violation,
        result.confidence,
        result.number_plate,
    )

    settings = get_settings()
    if not result.is_violation or result.confidence < settings.CONFIDENCE_THRESHOLD:
        logger.info(
            "Job %s skipped (confidence %.3f < threshold %.3f)",
            job_id,
            result.confidence,
            settings.CONFIDENCE_THRESHOLD,
        )
        return ProcessResponse(
            job_id=job_id,
            action="skipped",
            vision=vision_detail,
            violation_id=None,
            queue_remaining=remaining,
        )

    async with get_transaction() as tx:
        row = await insert_violation(
            tx,
            number_plate=result.number_plate,
            confidence_level=result.confidence,
            status="confirmed",
            evidence_image=job.get("image_path"),
            camera_id=camera_id,
            captured_at=captured_at,
        )

    violation_id = str(row["id"])
    logger.info("Job %s saved as violation %s", job_id, violation_id)

    _send_violation_email(
        image_bytes=image_bytes,
        image_path=job.get("image_path"),
        job_id=job_id,
        violation_id=violation_id,
        camera_id=camera_id,
        captured_at=captured_at,
        number_plate=result.number_plate,
        violation_type=result.violation_type,
        confidence=result.confidence,
    )

    return ProcessResponse(
        job_id=job_id,
        action="saved",
        vision=vision_detail,
        violation_id=violation_id,
        queue_remaining=remaining,
    )
